export interface Element {
    atomicMass: string,
    atomicNumber: number,
    atomicRadius: number,
    boilingPoint: number,
    bondingType: string,
    cpkHexColor: string,
    density: number,
    electronAffinity: number,
    electronegativity: number,
    electronicConfiguration: string,
    groupBlock: string,
    ionRadius: string,
    ionizationEnergy: number,
    meltingPoint: number,
    name: string,
    oxidationStates: number,
    standardState: string,
    symbol: string,
    vanDelWaalsRadius: string,
    yearDiscovered:any
}